apiVersion: v1
kind: ConfigMap

metadata:
  name: expense-config
  namespace: expense-dev

data:

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expense_db

  SPRING_PROFILES_ACTIVE: dev

  LOG_LEVEL: INFO

  TZ: Asia/Kolkata